"""initial voiceai schema and tables

Creates the ``voiceai`` schema (SQL Server only) and all seven tables. Written
by hand rather than autogenerated so it renders correctly on BOTH dialects:
GUID -> UNIQUEIDENTIFIER (SQL Server) / CHAR(36) (SQLite), and the schema is
applied only where supported. ``SCHEMA`` resolves per the active .env.

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-07
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.db.base import SCHEMA
from app.db.types import GUID

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _fk(target: str) -> str:
    return f"{SCHEMA}.{target}" if SCHEMA else target


def _ensure_schema() -> None:
    bind = op.get_bind()
    if SCHEMA and bind.dialect.name == "mssql":
        op.execute(
            f"IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = '{SCHEMA}') "
            f"EXEC('CREATE SCHEMA [{SCHEMA}]')"
        )


def _drop_schema() -> None:
    bind = op.get_bind()
    if SCHEMA and bind.dialect.name == "mssql":
        op.execute(f"DROP SCHEMA IF EXISTS [{SCHEMA}]")


def upgrade() -> None:
    _ensure_schema()

    op.create_table(
        "sessions",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("user_ref", sa.String(length=128), nullable=True),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_sessions"),
        schema=SCHEMA,
    )
    op.create_index("ix_sessions_user_ref", "sessions", ["user_ref"], schema=SCHEMA)

    op.create_table(
        "messages",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("session_id", GUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("input_type", sa.String(length=16), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("token_usage", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_messages"),
        sa.ForeignKeyConstraint(
            ["session_id"], [_fk("sessions.id")],
            name="fk_messages_session_id", ondelete="CASCADE",
        ),
        schema=SCHEMA,
    )
    op.create_index("ix_messages_session_id", "messages", ["session_id"], schema=SCHEMA)

    op.create_table(
        "retrievals",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("message_id", GUID(), nullable=False),
        sa.Column("chunk_id", sa.String(length=128), nullable=False),
        sa.Column("source", sa.String(length=512), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_retrievals"),
        sa.ForeignKeyConstraint(
            ["message_id"], [_fk("messages.id")],
            name="fk_retrievals_message_id", ondelete="CASCADE",
        ),
        schema=SCHEMA,
    )
    op.create_index("ix_retrievals_message_id", "retrievals", ["message_id"], schema=SCHEMA)

    op.create_table(
        "feedback",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("message_id", GUID(), nullable=False),
        sa.Column("rating", sa.String(length=8), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_feedback"),
        sa.ForeignKeyConstraint(
            ["message_id"], [_fk("messages.id")],
            name="fk_feedback_message_id", ondelete="CASCADE",
        ),
        schema=SCHEMA,
    )
    op.create_index("ix_feedback_message_id", "feedback", ["message_id"], schema=SCHEMA)

    op.create_table(
        "analytics",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("session_id", GUID(), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_analytics"),
        sa.ForeignKeyConstraint(
            ["session_id"], [_fk("sessions.id")],
            name="fk_analytics_session_id", ondelete="SET NULL",
        ),
        schema=SCHEMA,
    )
    op.create_index("ix_analytics_session_id", "analytics", ["session_id"], schema=SCHEMA)
    op.create_index("ix_analytics_event_type", "analytics", ["event_type"], schema=SCHEMA)

    op.create_table(
        "user_preferences",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("user_ref", sa.String(length=128), nullable=False),
        sa.Column("theme", sa.String(length=16), nullable=False),
        sa.Column("voice_enabled", sa.Boolean(), nullable=False),
        sa.Column("tts_voice", sa.String(length=64), nullable=True),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_user_preferences"),
        schema=SCHEMA,
    )
    op.create_index(
        "uq_user_preferences_user_ref", "user_preferences", ["user_ref"],
        unique=True, schema=SCHEMA,
    )

    op.create_table(
        "audit_logs",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=128), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_audit_logs"),
        schema=SCHEMA,
    )
    op.create_index("ix_audit_logs_actor", "audit_logs", ["actor"], schema=SCHEMA)


def downgrade() -> None:
    op.drop_table("audit_logs", schema=SCHEMA)
    op.drop_table("user_preferences", schema=SCHEMA)
    op.drop_table("analytics", schema=SCHEMA)
    op.drop_table("feedback", schema=SCHEMA)
    op.drop_table("retrievals", schema=SCHEMA)
    op.drop_table("messages", schema=SCHEMA)
    op.drop_table("sessions", schema=SCHEMA)
    _drop_schema()
